// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbrgntyiwuniovyoryta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJicmdudHlpd3VuaW92eW9yeXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDM5MDYsImV4cCI6MjA1ODU3OTkwNn0.zo6_Cr0CuRcBvX19QDNl0Ai6yA2oJfvarfdDm1-5nP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);